export const GET_TICKETS_LOADING  = "GET_TICKETS_LOADING"
export const GET_TICKETS_ERROR  = "GET_TICKETS_ERROR"
export const GET_TICKETS_SUCCESS  = "GET_TICKETS_SUCCESS"


export const PATCH_TICKETS_SUCCESS  = "PATCH_TICKETS_SUCCESS"
export const PATCH_TICKETS_LOADING  = "PATCH_TICKETS_LOADING"
export const PATCH_TICKETS_ERROR  = "PATCH_TICKETS_ERROR"

export const RESET_TICKETS_SUCCESS  = "RESET_TICKETS_SUCCESS"
export const RESET_TICKETS_LOADING  = "RESET_TICKETS_LOADING"
export const RESET_TICKETS_ERROR  = "PATCH_TICKETS_ERROR"